In [146]:
import numpy as np
import pandas as pd

In [147]:
!python dataTrainTest.py

num of train: 80
num of test: 21

In [148]:
train = pd.read_csv('data/math_score_train.csv')
test = pd.read_csv('data/math_score_test.csv')

train2 = pd.read_csv('data/math_score_train2.csv')
test2 = pd.read_csv('data/math_score_test2.csv')

train.head(2)

,grade,gender,interest,favor,chinese,patience,extras,study_hours,work_hours,club_hours,sleep_hours,commute_hours,score
0,0,0,3.0,2.0,4.0,2.0,0.0,0.5,0.0,3.5,5.5,2.5,90.0
1,1,1,3.0,4.0,3.0,2.0,2.5,0.5,0.5,0.0,5.5,0.5,63.0

In [149]:
class Paras:
    def __init__(self):

        ### parameters from SAS
        self.label = ["interest", "favor", "extras"]
        self.betas = [8.70888, -3.45130, 3.10016]
        self.beta0 = 57.32719

        self.num = len(self.label)

    def model(self, data):

        df = pd.DataFrame()
        df["label"] = data["score"]
        df["y_hat"] = data["score"]*0 + self.beta0

        for i in range(self.num):
            df["y_hat"] += self.betas[i]*data[self.label[i]]

        return df

    def fit(self, df):

        dof = df.shape[0] - self.num - 1
        print("DoF:", dof)

        sse_df = (df["label"] - df["y_hat"])**2
        sse = sse_df.sum()
        print("sum of square error:", np.round(sse,3))

        mse = sse/dof
        print("mean square error:",np.round(mse,5))

    def loss(self, df):

        sse_df = (df["label"] - df["y_hat"])**2
        sse = sse_df.sum()

        mse = sse/df.shape[0]
        print("mean square loss:",np.round(mse,5))
paras = Paras()

In [150]:
pred = paras.model(train)
paras.fit(pred)
pred.head(2)

DoF: 76
sum of square error: 14389.589
mean square error: 189.3367

   label     y_hat
0   90.0  76.55123
1   63.0  77.39903

In [151]:
pred = paras.model(test)
paras.loss(pred)
pred.head(2)

mean square loss: 207.50045

   label     y_hat
0   91.0  74.90621
1   80.0  70.24023